### PR TITLE
Add .copier-answers.yml to remember last answers

### PR DESCRIPTION
**Pull request by Yajo**
- If the copy destination exists and has a `.copierlog.yml`, all questions asked in the template `copier.yml` file will get the answer found in `.copierlog.yml` by default.
- For now, there are no `_private` variables in the copierlog, but in the future there might be, so I'm documenting that now.
- Add docs for some of Copier's hidden features.
- Add `to_nice_yaml` filter, to be able to dump beautiful YAML. [This name matches that on Ansible](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#filters-for-formatting-data) just in case somebody wants to share templates among both engines, although do not take that as an official support statement.
- Add a test that copies a folder with default data, then copies with altered data, and then copies again with default data and still the altered values have been used.
- This is a partial improvement towards completion of #88.

@Tecnativa TT20357

### CODE REVIEW

**Comment by pykong** [comment]
Thanks for this **PR**, this signifcantly enhances overall user experience!
I wonder would the entries be retrieved with lower latency if they were written to a `.sqlite` file instead?

**Comment by Yajo** [comment]
I think we should stick with YAML. This file will be git-tracked in most scenarios, and won't be very big. There are almost zero chances that one template asks so many questions that generates a file of more than 1MB here, so performance shouldn't be a bottleneck in this point. Using YAML seems the best option here.

**Comment by pykong** [comment]
What is the strategy for emptying the file? We need to prevent it getting swamped eventually.

**Comment by Yajo** [comment]
The file shouldn't be emptied. It should just get updated with latest answers after a normal update process.

Maybe you're getting confused by the "log" part of the name. It's not really a usage log, but an answers log. Maybe a name like `.copier-answers.yml` would be more intuitive?

**Comment by pykong** [comment]
`.copier-answers.yml` would better reflect the purpose of the file.
If it is supposed to live under the `copier` directory, you may shorten the file name to just
`answers.yml`. Or maybe make it `past-answers.yml`.

**Comment by Yajo** [comment]
> If it is supposed to live under the `copier` directory

Not, it's supposed to live in the `dst_path` root. I prefer a dot-prefixed file in any case (that's the most common practice for files that complement other projects (`.gitlab-ci.yml`, `.travis.yml`, `.editorconfig`, `.gitignore`... all start with dot)) and I'd also prefer some name that indicates specifically that this file comes from copier (just like those examples also). Ideas:

- `.copierlog.yml`, of course
- `.copied.yml`
- `.copier-answers.yml`
- `.copier-past-answers.yml`

Since the purpose is to keep a log of last answers, _and in the future it will not only contain answers_ (that's in an upcoming PR I have in the oven :wink:), and also keeping in mind it's a specific & short name, my vote still goes for `.copierlog.yml` (if that matters :sweat_smile:).

**Comment by pykong** [comment]
Make it `.copier-answers.yml`, then. Otherwise LGTME. 👍

**Comment by Yajo** [comment]
Changed now.

I wonder if you could please merge this. It's the only piece missing for opening the next PR.

**Comment by Yajo** [comment]
Well, it's done. The next iteration is #106. Please merge so we can move forward :pray: :innocent:

**Comment by Yajo** [comment]
Anything else here to be done to merge?

Thanks!

**Comment by pykong** [comment]
Sorry, for the delay. Switching to new workstation right now so I can finally develop again.
Thanks for the PR.

**Pull request merged**
