### PR TITLE
Auto coding standards (pre-commit and similar)

### PR DESCRIPTION
**Pull request by Yajo**
OK, as I keep on developing more here, I miss some tools I'm used to. I guess you'll love them, so let me propose them here.

This PR is divided into a logical commit sequence. If you review the diff, it will be scary, but if you go commit by commit, you'll understand it.

Summary:

1. Add and configure https://pre-commit.com/ (includes [black](https://github.com/psf/black), [isort](https://github.com/timothycrosley/isort), [prettier](https://prettier.io/) and [flake8-bugbear](https://github.com/PyCQA/flake8-bugbear), among others). Also add and configure [`.editorconfig`](https://editorconfig.org/), which doesn't have a direct effect in linters, but autoconfigures most code editors to write code as expected.
1. Add a specific change for some tests that were relying in files that didn't end with an EOF<sup>1</sup>. I think this test is useful as it is, because it makes sure Copier doesn't add those by default, so I ended up adding support to skip the EOF fix if a file contains `.noeof.` in its name. I renamed the needed files and fixed their tests.
1. Run pre-commit and commit its diff. This is the biggest diff, but I didn't touch a line manually.
1. The new linters showed up some failures/warnings that I fixed/ignored too.
1. I added a couple of configurations that make development under vscode more delightful, as I guess by #101 that you also use it.

@Tecnativa TT20357

---

<sup>1</sup> There's a hook called `end-of-file-fixer` which makes sure there's just 1 `\n` character at the end of each file. It adds or removes automatically in any case. This was breaking some tests.

### CODE REVIEW

**Comment by pykong** [comment]
@Yajo Great to have you on board.
As a matter of fact I am also a heavy user of `pre-commit`.
I have been reluctant to include `pre-commit` because I do not want to impose too much of my own dev-setup onto other potential devs.

However having some basic git hooks (black, flake8, isort, ...) in place would be helpful.
I'll take care of that on the weekend.

**Comment by Yajo** [comment]
>  I see you have a **PR** in the makings in regards to that.
> I am going to check it once ready.

Yes, this is the PR and AFAICS it's ready to merge :blush:

**Comment by Yajo** [comment]
I updated this PR because it had conflicts. It will keep on getting conflicts as the project evolves because it affects almost all the codebase.

Would you mind merging ASAP please so I can stop adding rebases here? :pray: :innocent:

**Comment by pykong** [comment]
@Yajo Sorry for the delayed response. My new workstation is getting me a lot of trouble.
Please resolve the conflicts and I am ready to merge this.

**Comment by Yajo** [comment]
Yeah, Black Friday has its problems too :yum: 

Rebased again.

**Comment by Yajo** [comment]
:joy_cat:

**Comment by pykong** [comment]
Thanks for this **PR**. Merged.

**Pull request merged**
